#if defined _nd_resources_included
  #endinput
#endif
#define _nd_resources_included

#define RESOURCE_PRIME 			0
#define RESOURCE_SECONDARY 		1
#define RESOURCE_TERTIARY		2

#define RES_PRIME_START			80000
#define RES_PRIME_EXTRACT		3000
#define RES_PRIME_TRICKLE		1350

#define RES_SECONDARY_START		44000
#define RES_SECONDARY_EXTRACT	1650
#define RES_SECONDARY_TRICKLE	743

#define RES_TERTIARY_START		16000
#define RES_TERTIARY_EXTRACT	600
#define RES_TERTIARY_TRICKLE	270