#if defined _nd_structures_included
  #endinput
#endif
#define _nd_structures_included

enum ND_Structures {
	Command_Bunker,
	MG_Turret,
	Transport_Gate,
	Power_Plant,
	Wireless_Repeater,
	Relay_Tower,
	Supply_Station,
	Assembler,
	Armory,
	Artillery,
	Radar_Station,
	FT_Turret,
	Sonic_Turret,
	Rocket_Turret,
	Wall,
	Barrier
}

#define STRUCT_BUNKER "struct_command_bunker"
#define STRUCT_ASSEMBLER "struct_assembler"
#define STRUCT_TRANSPORT "struct_transport_gate"
#define STRUCT_ARTILLERY "struct_artillery_explosion"
#define STRUCT_SONIC_TURRET "struct_sonic_turret"
#define STRUCT_FT_TURRET "struct_flamethrower_turret"
#define STRUCT_POWER_STATION "struct_power_station"
#define STRUCT_ARMOURY "struct_armoury"
#define STRUCT_RADAR "struct_radar"
#define STRUCT_MG_TURRET "struct_machinegun_turret"
#define STRUCT_ROCKET_TURRET "struct_rocket_turret"
#define STRUCT_SUPPLY "struct_support_station"
